name: Cloud Resume Azure Storage Static Website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite --account-name "jpolanskyresumedev" --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "Resume-Dev" --name "jpolanskyresumedev" --resource-group "Resume_Dev"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
